name: Update Articles

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Update articles
        run: npm run update-articles

      - name: Check for changes
        id: check-for-changes
        shell: bash {0}
        run: |
          git diff --exit-code
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "No changes detected"
            exit 0
          elif [ $exit_code -eq 1 ]; then
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            echo "Changes detected"
            exit 0
          fi
          echo "An error occurred"
          exit $exit_code

      - name: Check for existing PR
        if: ${{ steps.check-for-changes.outputs.exit_code == '1' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check-pr
        run: |
          existing_pr=$(gh pr list --search "Update articles - is:open" in:title --json number --jq length)
          if [ "$existing_pr" -gt "0" ]; then
            echo "existing_pr=true" >> $GITHUB_OUTPUT
            echo "Found existing open Update Articles PR, skipping PR creation"
            exit 0
          fi
          echo "existing_pr=false" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.check-for-changes.outputs.exit_code == '1' && steps.check-pr.outputs.existing_pr == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
        run: |
          current_datetime=$(date +"%Y-%m-%d %H:%M:%S")
          branch_name="update-articles/$(date +%Y-%m-%d-%H-%M-%S)"
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git checkout -b $branch_name
          git add .
          git commit -m "Update articles - $current_datetime"
          git push origin $branch_name
          
          gh pr create \
            --title "Update articles - $current_datetime" \
            --body "This PR was automatically created by the Update Articles workflow." \
            --base main \
            --head $branch_name
