name: Update Articles

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Update articles
        run: npm run update-articles

      - name: Check for changes
        id: check-for-changes
        shell: bash {0}
        run: |
          git diff --exit-code
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "No changes detected"
            exit 0
          elif [ $exit_code -eq 1 ]; then
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            echo "Changes detected"
            exit 0
          fi
          echo "An error occurred"
          exit $exit_code

      - name: Commit changes
        if: ${{ steps.check-for-changes.outputs.exit_code == '1' }}
        env:
          TZ: 'Asia/Tokyo'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          current_datetime=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Update articles - $current_datetime"
          git push
